name: Deploy Spring Boot to VPS with PostgreSQL

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}



    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.DEPLOYUSER_VPS_SECRET }}
        port: 49159
        script: |
          cd /home/deployuser/api-portfolio
          
          # Pull the latest Spring Boot image
          docker pull osahraoui70/api-portfolio:latest
          
          # Pull PostgreSQL if necessary
          docker pull postgres:13
          
          # Stop and remove old containers
          docker-compose down
          
          # Start the containers again
          docker-compose up -d
          
          # Check if the containers are running
          docker ps
